; PlatformIO Project Configuration File
;
; Bell_shaker (Teensy MicroMod)

[platformio]
default_envs = teensymm

[env:teensymm]
platform = teensy
board = teensymm
framework = arduino
upload_protocol = teensy-cli
monitor_port = /dev/ttyACM*
monitor_speed = 115200
monitor_dtr = 0
monitor_rts = 0

lib_deps =
    mjbots/Moteus@1.0.2
    pierremolinaro/ACAN2517FD@^2.1.5
