; PlatformIO Project Configuration File
; Hidden Sound Path — MicroMod Teensy (Teensy 4.0 기반) + SGTL5000

[env:micromod_teensy]
platform = teensy
board = teensy40
framework = arduino
upload_protocol = teensy-cli
monitor_speed = 115200
lib_ldf_mode = deep+
