; PlatformIO Project Configuration File
; Audio Shield Controller — Teensy 4.0 + SGTL5000

[env:teensy40]
platform = teensy
board = teensy40
framework = arduino
upload_protocol = teensy-cli
monitor_speed = 115200
lib_ldf_mode = deep+
