[env:teensy40]
platform  = teensy
board     = teensy40
framework = arduino
upload_protocol = teensy-cli
lib_deps =
    adafruit/Adafruit MLX90614 Library
    adafruit/Adafruit SSD1306
    adafruit/Adafruit GFX Library
